{{- if or .Values.oidc.enabled .Values.saml.enabled }}
{{- if and (not .Values.oidc.rbac.enabled) (not .Values.saml.rbac.enabled) }}
{{- if or .Values.oidc.rbac.teamsEnabled .Values.saml.rbac.teamsEnabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kubecost-rbac-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
stringData:
  key:
    {{- if .Values.oidc.enabled }}
    {{ .Values.oidc.authSecret | default (randAlphaNum 32 | quote) }}
    {{- end }}
    {{- if .Values.saml.enabled }}
    {{ .Values.saml.authSecret | default (randAlphaNum 32 | quote) }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
